# Generated by Django 2.2.4 on 2019-08-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20190813_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='witdrawal',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
