# Generated by Django 2.2.4 on 2019-08-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20190813_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='witdrawal',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
