# Generated by Django 2.2.4 on 2019-08-13 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
        ('payments', '0005_auto_20190813_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenue',
            name='pending',
        ),
        migrations.RemoveField(
            model_name='witdrawal',
            name='pending',
        ),
        migrations.AddField(
            model_name='revenue',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='witdrawal',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_by_user', to=settings.AUTH_USER_MODEL)),
                ('payment_for', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.Product')),
            ],
        ),
    ]
