# Generated by Django 2.2.4 on 2019-08-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190813_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Bello', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Mayowa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='pending_payments',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='0812358600', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='bmayowa25', max_length=120, unique=True),
            preserve_default=False,
        ),
    ]
